.PHONY: clean All

All:
	@echo "----------Building project:[ Amazon - Debug ]----------"
	@cd "Amazon" && $(MAKE) -f  "Amazon.mk"
clean:
	@echo "----------Cleaning project:[ Amazon - Debug ]----------"
	@cd "Amazon" && $(MAKE) -f  "Amazon.mk" clean
